<?php

namespace App\Command;

use App\Classe\Mail;
use App\Entity\BourseArmes;
use App\Service\FluctuationBourseArmesService;
use App\Service\SupplierUpdaterService;
use DOMDocument;
use DOMXPath;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Sunra\PhpSimple\HtmlDomParser;

#[AsCommand(
    name: 'app:SupplierUpdaterToolBox',
    description: 'Mise à jour produits fournisseurs',
)]
class SupplierUpdateToolBoxCommand extends Command
{
    protected $supplier;
    /**
     * RunCommand constructor.
     * @param SupplierUpdaterService $bourse
     */
    public function __construct(SupplierUpdaterService $supplier) //constructeur
    {
        $this->supplier = $supplier;
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        echo "Insertion produits TOOLBOX\n";

	$bgm1 = [
		 ['url' => 'https://bgmwinfield.fr/generation-5/2404-glock-19-gen5-fs-mos.html'],
	];
        $bgm = [
            ["url" => 'https://bgmwinfield.fr/OTIS/2861-kit-de-nettoyage-mpsr-7-62-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2860-kit-de-nettoyage-mpsr-5-56-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2848-5-56-7-62-9mm-i-mod-cleaning-kit-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2852-7-62mm-i-mod-cleaning-kit-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2859-kit-de-nettoyage-defender-9mm-7-62-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2923-kit-de-nettoyage-en-mallette-9mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2933-kit-de-nettoyage-deluxe-cal-7-62-5-56-9mm-45-12ga-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2853-9mm-i-mod-cleaning-kit-otis.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2480-garde-main-geissele-mk14-13-ddc.html'],
            ["url" => "https://bgmwinfield.fr/TROY/2946-troy-m4a4-socc-cqb-223-rem-10-5-socc-9-25.html"],
            ["url" => "https://bgmwinfield.fr/TROY/2944-troy-m4a4-socc-sba3-223-rem-10-socc-9-25.html"],
            ["url" => "https://bgmwinfield.fr/TROY/2940-troy-par-300-blk-sporting-pump-action-rifle-16-optic-ready.html"],
            ["url" =>"https://bgmwinfield.fr/TROY/2945-troy-m5-carbine-cal-9mm-105-compatible-chargeur-glock.html"],
            ["url" =>"https://bgmwinfield.fr/TROY/3165-troy-308-par-sporting-pump-action-rifle-calibre-308-win-18-2940.html"],
            ["url" =>"https://bgmwinfield.fr/TROY/2941-troy-222-par-sporting-pump-action-rifle-calibre-222-rem-18.html"],
            ["url" =>"https://bgmwinfield.fr/TROY/2942-troy-spr222-sporting-straight-pull-rifle-calibre-222-rem-18.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-M/1935-robinson-armament-xcr-m-standard-canon-de-186-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-M/1934-robinson-armament-xcr-m-standard-canon-de-16-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-M/1933-robinson-armament-xcr-m-mini-canon-de-13-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-M/1932-robinson-armament-xcr-m-micro-canon-de-95-sable.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-M/1931-robinson-armament-xcr-m-micro-canon-de-95-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/2329-robinson-armament-xcr-l-standard-canon-de-16-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1930-robinson-armament-xcr-l-standard-canon-de-147-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1929-robinson-armament-xcr-l-standard-canon-de-12-sable.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1928-robinson-armament-xcr-l-standard-canon-de-12-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1927-robinson-armament-xcr-l-standard-canon-de-95-sable.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1926-robinson-armament-xcr-l-standard-canon-de-95-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1925-robinson-armament-xcr-l-mini-canon-de-10-sable.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1924-robinson-armament-xcr-l-mini-canon-de-10-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1923-robinson-armament-xcr-l-mini-canon-de-75-noir.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1922-robinson-armament-xcr-l-micro-canon-de-75-noir-1.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1921-robinson-armament-xcr-l-micro-canon-de-75-sable.html"],
            ["url" =>"https://bgmwinfield.fr/XCR-L/1920-robinson-armament-xcr-l-micro-canon-de-75-noir.html"],
            ["url" =>"https://bgmwinfield.fr/bravo-company-usa/2065-bcm-mk12-mod0-a5-spr.html"],
            ["url" =>"https://bgmwinfield.fr/bravo-company-usa/2668-bravo-company-bcm-recce-18-mcmr-precision-rifle.html"],
            ["url" =>"https://bgmwinfield.fr/bravo-company-usa/2104-bcm4-cqb9-kmr-a8-300blk-2104.html"],
            ["url" =>"https://bgmwinfield.fr/bravo-company-usa/2670-bcm4-cqb11-kmr-a10.html"],
            ["url" =>"https://bgmwinfield.fr/bravo-company-usa/3240-bcm-conversion-bcm4-300-blk-9.html"],
            ["url" =>"https://bgmwinfield.fr/bravo-company-usa/2277-conversion-bcm4-cqb11-elw-kmr-a10.html"],
            ["url" =>"https://bgmwinfield.fr/tippmann-arms/4027-tippmann-m4-22-pro-mmssaelf-canon-flute-16-cal22lr.html"],
            ["url" =>"https://bgmwinfield.fr/tippmann-arms/4026-tippmann-m4-22-elite-l-canon-16-cal22lr-fde.html"],
            ["url" =>"https://bgmwinfield.fr/tippmann-arms/4025-tippmann-m4-22-delta-elite-l-canon-flute-16-cal22lr.html"],
            ["url" =>"https://bgmwinfield.fr/tippmann-arms/4024-tippmann-m4-22-elite-s-canon-125-cal22lr.html"],
            ["url" =>"https://bgmwinfield.fr/tippmann-arms/4023-tippmann-m4-22-pro-s-canon-125-cal22lr.html"],
            ["url" =>"https://bgmwinfield.fr/tippmann-arms/4022-tippmann-m4-22-pro-l-canon-16-cal22lr.html"],
            ["url" =>"https://bgmwinfield.fr/faxon-firearms/4015-faxon-compensateur-pistolet-exos-523-pour-glock-43.html"],
            ["url" =>"https://bgmwinfield.fr/nouveautes/3782-faxon-firearms-ff-15-ascent-cal223-rem-canon-105.html"],
            ["url" =>"https://bgmwinfield.fr/faxon-firearms/3570-faxon-firearms-ff-15-ascent-msr-carabine-cal223-rem-canon-16.html"],
            ["url" =>"https://bgmwinfield.fr/faxon-firearms/3776-faxon-firearms-ff9f-bantam-16-pcc-calibre-9mm.html"],
            ["url" =>"https://bgmwinfield.fr/faxon-firearms/3571-faxon-firearms-ff-15-sentry-msr-cal223-rem-canon-16.html"],
            ["url" =>"https://bgmwinfield.fr/keltec/586-keltec-pmr30-22-magnum-couleur-noire-avec-cache-flamme.html"],
            ["url" =>"https://bgmwinfield.fr/keltec/2602-keltec-cp33-calibre-22lr.html"],
            ["url" =>"https://bgmwinfield.fr/keltec/1046-keltec-pmr30-22-magnum-couleur-tan-990.html"],
            ["url" =>"https://bgmwinfield.fr/keltec/1047-keltec-pmr30-22-magnum-couleur-noire-586.html"],
            ["url" =>"https://bgmwinfield.fr/keltec/1292-keltec-pf-9-9mm.html"],
            ["url" =>"https://bgmwinfield.fr/keltec/3031-keltec-p17-22lr.html"],
            ["url" =>"https://bgmwinfield.fr/tactical-solutions/1520-tactical-solutions-tsg-22-avec-canon-filete-pour-glock-19-23-32-38.html"],
            ["url" =>"https://bgmwinfield.fr/tactical-solutions/1394-tactical-solutions-tsg-22-avec-canon-filete-pour-glock-17-22-31-34-35-37.html"],
            ["url" =>"https://bgmwinfield.fr/tactical-solutions/1521-tactical-solutions-tsg-22-pour-glock-19-23-32-38.html"],
            ["url" =>"https://bgmwinfield.fr/tactical-solutions/1395-tactical-solutions-tsg-22-pour-glock-17-22-31-34-35-37.html"],
            ["url" =>"https://bgmwinfield.fr/tactical-solutions/1388-tactical-solutions-pac-lite-45-filete.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3451-glock-zaffiri-custom-34-gen4-zps6-midnight-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3450-glock-zaffiri-custom-34-gen4-zps2-midnight-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3405-zaffiri-glock-43-gen3-ported-tin-burnt-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3447-glock-zaffiri-custom-43x-stone.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3446-glock-zaffiri-custom-43x-midnight-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3449-glock-zaffiri-custom-17-gen5-rmr-midnight-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/zaffiri-precision/3448-glock-zaffiri-custom-19-gen5-stone.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2619-l2d-canon-match-pour-glock-34-gen3-gen4-filete-en-1-2x28-dlc-noir.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2618-l2d-canon-match-pour-glock-19-gen3-gen4-filete-en-1-2x28-dlc-noir.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2617-l2d-canon-match-pour-glock-19-gen3-gen4-filete-en-1-2x28-pvd-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2616-l2d-canon-match-pour-glock-19-gen3-gen4-filete-en-1-2x28-cameleon.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2615-l2d-canon-match-pour-glock-19-gen3-gen4-filete-en-1-2x28-acier-inoxydable.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2614-l2d-canon-match-pour-glock-17-gen3-gen4-filete-en-1-2x28-pvd-bronze.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2613-l2d-canon-match-pour-glock-17-gen3-gen4-filete-en-1-2x28-cameleon.html"],
            ["url" =>"https://bgmwinfield.fr/l2d-combat/2612-l2d-canon-match-pour-glock-17-gen3-gen4-filete-en-1-2x28-acier-inoxydable.html"],
            ["url" =>"https://bgmwinfield.fr/wilson-combat/3440-wilson-combat-pistolet-sigwilson-p320-full-size-detente-droite.html"],
            ["url" =>"https://bgmwinfield.fr/wilson-combat/3439-wilson-combat-pistolet-sigwilson-p320-carry-detente-droite.html"],
            ["url" => "https://bgmwinfield.fr/TROY/2947-troy-m10a1-socc-cal-308-win-16-socc-13.html"],
            ["url" => "https://bgmwinfield.fr/angstadt-arms/2368-angstadt-arms-udp-9-sbr11.html"],
            ["url" => "https://bgmwinfield.fr/angstadt-arms/2327-angstadt-arms-udp-9-rifle-16.html"],
            ["url" => 'https://bgmwinfield.fr/angstadt-arms/2369-angstadt-arms-udp-9-pdw11.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2868-kit-de-nettoyage-patriot-9mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/moderateurs-de-son/1557-b-t-moderateur-de-son-rotex-iia-30308-300-aac.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2848-5-56-7-62-9mm-i-mod-cleaning-kit-otis.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/2917-garde-main-urx-31-1075-knights-armament.html'],
            ["url" => 'https://bgmwinfield.fr/rainier-arms/2610-rainier-arms-precision-rifle-canon-inox-fibre-de-carbone-24-cal-308win.html'],
            ["url" => 'https://bgmwinfield.fr/nouveautes/3766-chisel-machining-marlin-lever-action-skeletonized-aluminum-stock.html'],
            ["url" => 'https://bgmwinfield.fr/nouveautes/3765-chisel-machining-henry-lever-action-skeletonized-aluminum-stock.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2482-garde-main-geissele-mk7-127-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/3419-tactical-evo-bipied-tk3-noir.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/3418-tactical-evo-bipied-tk3-fde.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2481-garde-main-geissele-mk7-127-noir.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2480-garde-main-geissele-mk14-13-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2479-garde-main-geissele-mk14-95-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/2917-garde-main-urx-31-1075-knights-armament.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/2915-garde-main-urx-31-15-knights-armament.html'],
            ["url" => 'https://bgmwinfield.fr/armes-d-epaule/3221-elftmann-tactical-rem-700-precision-rifle-trigger-w-safety-internal-bolt-release-black-shoe.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/3483-geissele-garde-main-flottant-mk8-93-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2478-garde-main-geissele-mk14-95-noir.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2477-garde-main-geissele-mk14-7-noir.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2493-crosse-magpul-hunter-700-rem-700-short-action-fde.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2492-crosse-magpul-hunter-700-rem-700-short-action-noire.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2026-crosse-magpul-prs-gen3-noire.html'],
            ["url" => 'https://bgmwinfield.fr/geissele-automatics/3484-geissele-garde-main-flottant-mk4-93-blk.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3273-battlearms-bad-tt-15-s-adjustable-frictionless-trigger-straight.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3272-battlearms-bad-tt-15-c-adjustable-frictionless-trigger-curved.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/823-samson-garde-main-flottant-star-mx-10.html'],
            ["url" => 'https://bgmwinfield.fr/nouveautes/3767-chisel-machining-marlin-lever-action-aluminum-handguard.html'],
            ["url" => 'https://bgmwinfield.fr/moderateurs-de-son/2121-bt-tiger-light-338.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2047-garde-main-alg-defense-emr-v3-m-lok-10-gris-2045.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/2031-precision-armament-efab-cal-308.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/2030-precision-armament-efab-cal-223.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/635-b-t-accessoires-poignee-bipieds-qd.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/1710-mka-1919-garde-main-pica-et-keymod.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/3234-lantac-dragon-compensateur-9mm-1-2x28.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/3233-lantac-dragon-compensateur-9mm-1-2x36.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1688-lantac-dragon-dgn762b.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1687-lantac-dragon-dgn556b.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/2330-garde-main-samson-flottant-evolution-9.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/1888-precision-armament-m-11-severe-duty-cal-308-1887.html'],
            ["url" => 'https://bgmwinfield.fr/nouveautes/3891-phase-5-fatman-hex-brake-556.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/2397-magpul-bipied-m-lok-noir.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/707-samson-garde-main-flottant-evolution-7.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1686-primary-weapons-systems-fsc556.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/3660-ulfhednar-plaque-de-couche-ajustable.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2488-magpul-crosse-sga-mossberg-500-590-590a1-sable.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2119-magpul-crosse-sga-mossberg-500-590-590a1-noire.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/1939-bipied-b-t-pieds-a-crampons.html'],
            ["url" => 'https://bgmwinfield.fr/geissele-automatics/3486-geissele-levier-d-armement-sch-556-ambidextre-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/geissele-automatics/3487-geissele-levier-d-armement-ach-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1887-precision-armament-m4-72-severe-duty-cal-223.html'],
            ["url" => 'https://bgmwinfield.fr/Lampes/1313-lampe-cl-43-keltec.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/3225-xtreme-tact-compensateur-223r.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/3224-vg6-precision-compensateur-9mm-1-2x28-gamma.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3281-battlearms-rack-charging-handle-ar308.html'],
            ["url" => 'https://bgmwinfield.fr/divers/3663-ulfhednar-adaptateur-loke-picatinny.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2490-crosse-magpul-pour-ak-moe-noire.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3284-battlearms-thumper-muzzle-device-black-nitride-9mm.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3283-battlearms-thumper-muzzle-device-black-nitride-30cal.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3282-battlearms-thumper-muzzle-device-black-nitride-22cal.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/2341-poignee-magpul-miad-grip-type-2-fde.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/2333-magpul-afg2-angled-fore-grip-couleur-fde.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/2000-poignee-magpul-miad-gen-1-1-type-1-grise.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/1335-poignee-magpul-miad-gen-1-1-type-1-noire.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/1334-poignee-magpul-miad-grip-type-2-noire.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/3646-bcm-gf-grip-mod-0-fde.html'],
            ["url" => 'https://bgmwinfield.fr/Lampes/3033-clip-picatinny-pour-lampe-cl-42-keltec.html'],
            ["url" => 'https://bgmwinfield.fr/Divers/2977-thompson-center-encore-pro-hunter-trigger-spring-kit-mcarbo.html'],
            ["url" => 'https://bgmwinfield.fr/bretelles-et-attache-bretelles/1340-attache-bretelle-rsa-pour-rail-picatinny-magpul-1338-1339.html'],
            ["url" => 'https://bgmwinfield.fr/bretelles-et-attache-bretelles/1338-attache-bretelle-rsa-qd-pour-rail-picatinny-magpul.html'],
            ["url" => 'https://bgmwinfield.fr/poignees-et-bipieds/2217-bcm-gunfighter-grip-mod-1-noire.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/1085-keltec-rehausse-picatinny-rfb.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/1612-kit-compensateur-pour-plr-16-et-su-16-keltec.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/3179-troy-cache-flamme-308-nato-5-8x24-avec-rondelle.html'],
            ["url" => 'https://bgmwinfield.fr/Magpul/2501-poignee-pour-rail-picatinny-magpul.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3739-cmmg-zeroed-pistol-grip.html'],
            ["url" => 'https://bgmwinfield.fr/bretelles-et-attache-bretelles/2503-m-lok-qd-sling-mount.html'],
            ["url" => 'https://bgmwinfield.fr/Chargeurs/2498-magpul-coupleur-de-chargeurs-ar15.html'],
            ["url" => 'https://bgmwinfield.fr/accessoires-m-lok/2339-magpul-rail-m-lok-5-slots-2080.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/1560-offset-rail-2-2-samson.html'],
            ["url" => 'https://bgmwinfield.fr/battle-arms-development/3274-battlearms-adjustable-tactical-grip-black.html'],
            ["url" => 'https://bgmwinfield.fr/produits/3166-nettoyage-pour-silencieux-500ml-schletek.html'],
            ["url" => 'https://bgmwinfield.fr/crosses-pour-ar-15-et-ar-10/3036-enhanced-rubber-butt-pad-magpul.html'],
            ["url" => 'https://bgmwinfield.fr/2a-armament/2108-2a-armament-xanthos-lite-xlr-18.html'],
            ["url" => 'https://bgmwinfield.fr/2a-armament/2107-2a-armament-balios-lite-105.html'],
            ["url" => 'https://bgmwinfield.fr/2a-armament/2106-2a-armament-balios-lite-75.html'],
            ["url" => 'https://bgmwinfield.fr/2a-armament/2105-2a-armament-balios-lite-300blk-8.html'],
            ["url" => 'https://bgmwinfield.fr/Lynx/1891-lynx-td15-inox-cal-308-win.html'],
            ["url" => 'https://bgmwinfield.fr/Lynx/1894-lynx-td15-acier-bronze-cal-308-win.html'],
            ["url" => 'https://bgmwinfield.fr/Noveske/2025-noveske-n4-light-recce-14-5.html'],
            ["url" => 'https://bgmwinfield.fr/rainier-arms/2610-rainier-arms-precision-rifle-canon-inox-fibre-de-carbone-24-cal-308win.html'],
            ["url" => 'https://bgmwinfield.fr/wilson-combat/3445-wilson-combat-super-sniper-carabine-cal223-wylde-canon-flute-20.html'],
            ["url" => 'https://bgmwinfield.fr/wilson-combat/3442-wilson-combat-protector-pistol-carabine-cal223-rem-canon-113.html'],
            ["url" => 'https://bgmwinfield.fr/wilson-combat/3441-wilson-combat-protector-carabine-cal223-rem-canon-16.html'],
            ["url" => 'https://bgmwinfield.fr/wilson-combat/3444-wilson-combat-protector-s-carabine-cal223-rem-canon-16.html'],
            ["url" => 'https://bgmwinfield.fr/wilson-combat/3443-wilson-combat-protector-pistol-carabine-cal9mm-canon-8.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1619-windham-weaponry-ww-15-ref-r16mlsfs3g-7.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1623-windham-weaponry-modele-ww-308-ref-r18fsfst-308.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1624-windham-weaponry-modele-ww-308-ref-r16sfst-308.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1625-windham-weaponry-modele-ww-308-src-ref-r18fft-308.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2311-windham-weaponry-ww-15-ref-r9sfst-7-300m.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2556-windham-weaponry-r9sfst-9mm.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2430-windham-weaponry-ww-15-cal-450-bushmaster-16.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2374-windham-weaponry-ww-15-ref-r16m4ftt-762.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/3986-windham-weaponry-20-varmint.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1622-windham-weaponry-ww-15-ref-r14m4sfst-7-mi.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1618-windham-weaponry-ww-15-ref-r11sfst-7.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1620-windham-weaponry-ww-15-ref-r20gvta4s-7.html'],
            ["url" => 'https://bgmwinfield.fr/Conversions/2429-windham-weaponry-conversion-ww-15-16-3g.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2552-windham-weaponry-ww-15-superlight.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/1621-windham-weaponry-ww-15-ref-r14m4-7a4t.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2375-windham-weaponry-ww-15-ref-ur16m4ftb-762.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2360-windham-weaponry-ww-15-ref-ur9sfsb-300-7m.html'],
            ["url" => 'https://bgmwinfield.fr/Conversions/2433-conversion-windham-weaponry-ww-15-cal-450-bushmaster-9.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2358-windham-weaponry-conversion-ww-15-115.html'],
            ["url" => 'https://bgmwinfield.fr/Conversions/2431-conversion-windham-weaponry-ww-15-cal-450-bushmaster-pour-ar-15.html'],
            ["url" => 'https://bgmwinfield.fr/windham-weaponry/2360-windham-weaponry-ww-15-ref-ur9sfsb-300-7m.html'],
            ["url" => 'https://bgmwinfield.fr/Conversions/2433-conversion-windham-weaponry-ww-15-cal-450-bushmaster-9.html'],
            ["url" => 'https://bgmwinfield.fr/Conversions/2432-conversion-windham-weaponry-ww-15-20-govt.html'],
            ["url" => 'https://bgmwinfield.fr/armes-d-epaule/2551-windham-weaponry-ww-15-superlight-src.html'],
            ["url" => 'https://bgmwinfield.fr/XBR/1818-xbr-modele-fr-15-alg-v3-grey-145-.html'],
            ["url" => 'https://bgmwinfield.fr/XBR/1905-xbr-conversion-fr-15-14-5-alg-v3-noir.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/2248-cmmg-endeavor-mk3-6-5-creedmoor-20.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3849-cmmg-carabine-mkg-45-acp-8.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3060-cmmg-conversion-mkgs-9mm-16.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3059-cmmg-conversion-mkgs-9mm-8.html'],
            ["url" => 'https://bgmwinfield.fr/Conversions/2398-conversion-cmmg-banshee-mk4-300blk.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3627-cmmg-upper-group-banshee-200-mk4-556x45.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3053-cmmg-conversion-mk4-22lr-16.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/2370-cmmg-conversion-banshee-mk4-22lr.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3848-cmmg-compensateur-a2-58x24.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3858-cmmg-carabine-mk47-762x39-banshee-8-charcoal-green.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3859-cmmg-carabine-mk47-762x39-banshee-8-midnight-bronze.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3857-cmmg-carabine-mk47-762x39-banshee-8-coyote-tan.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3856-cmmg-carabine-mk47-762x39-banshee-8.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3854-cmmg-carabine-mk47-762x39-banshee-125-midnight-bronze.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3853-cmmg-carabine-mk47-762x39-banshee-125-coyote-tan.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3852-cmmg-carabine-mk47-762x39-banshee-125-charcoal-green.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3851-cmmg-carabine-mk47-762x39-banshee-125.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/2248-cmmg-endeavor-mk3-6-5-creedmoor-20.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3849-cmmg-carabine-mkg-45-acp-8.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3579-cmmg-carabine-mk4-k-cal-223-125p-sniper-gray.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3620-cmmg-carabine-banshee-100-mk9-9mm-rdbcolt.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3835-cmmg-carabine-mk4-300-aac-banshee-200-8-pistol-black.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3578-cmmg-carabine-mk4-k-cal-223-125p-midnight-bronze.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3045-cmmg-mk4-banshee-100-300-blk-nfa.html'],
            ["url" => 'https://bgmwinfield.fr/CMMG/3836-cmmg-carabine-mkgs-drb-9mm-16-chargeur-glock-odg.html'],
            ["url" => 'https://bgmwinfield.fr/KelTec/2669-keltec-sub-2000-multi-mag.html'],
            ["url" => 'https://bgmwinfield.fr/KelTec/1691-keltec-sub-2000-gen2-cal-9x19.html'],
            ["url" => 'https://bgmwinfield.fr/KelTec/1701-keltec-cmr-30.html'],
            ["url" => 'https://bgmwinfield.fr/KelTec/989-keltec-rfb-avec-cache-flamme-308win-7-62-otan.html'],
            ["url" => 'https://bgmwinfield.fr/bt/661-lampe-bt-modele-wmlx-b-w-l-gen2-800-lumens.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/739-aimpoint-micro-t1-2moa-pour-ar15-ref-12417.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/570-aimpoint-bonnette-d-oculaire-transparente-ref-12240.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/569-bonnette-d-objectif-transparente-aimpoint.html'],
            // ["url" => 'https://bgmwinfield.fr/Aimpoint/345-aimpoint-ceu.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/568-bonnette-anti-reflexion-aimpoint.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/566-aimpoint-entretoise-30mm-pour-microt1-ref-12357.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/2371-aimpoint-compm5-avec-entretoise-de-39mm-et-montage-fixe.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/739-aimpoint-micro-t1-2moa-pour-ar15-ref-12417.html'],
            ["url" => 'https://bgmwinfield.fr/C-More/546-c-more-viseur-serendipity-sl830.html'],
            ["url" => 'https://bgmwinfield.fr/geissele-automatics/2823-geissele-lunette-super-precision-1-6-dmmr-1.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3413-meprolight-foresight.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3409-meprolight-rds-pro-v2-red-dot-2-moa.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3412-meprolight-mx3-t.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3411-meprolight-mx3-f.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3410-meprolight-tru-dot-rds-2-moa.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3460-meprolight-micrords-3-moa-pour-glock-mos.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3461-meprolight-micro-rds-3-moa-avec-montage-picatinny.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3414-meprolight-evergreen-glock-17-19-42-43-hausse-verte-guidon-orange.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3417-meprolight-evergreen-sig-p320-p226-hausse-noire-guidon-orange.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3416-meprolight-evergreen-cz75-hausse-noire-guidon-orange.html'],
            ["url" => 'https://bgmwinfield.fr/Meprolight/3415-meprolight-evergreen-glock-17-19-42-43-hausse-noire-guidon-vert.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3325-swampfox-sentinel-red-dot-3moa.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3324-swampfox-kingslayer-red-dot.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3323-swampfox-justice-red-dot-3-moa.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3335-swampfox-cantilever-30mm.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3333-swampfox-collier-34mm-high-1.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3331-swampfox-collier-30mm-high.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3330-swampfox-collier-30mm-ext-high-1.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3332-swampfox-collier-34mm-ext-high-1.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3329-swampfox-collier-34mm-high.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3328-swampfox-collier-34mm-ext-high.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3334-swampfox-collier-30mm-bas.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3327-swampfox-collier-30-mm-haut.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3326-swampfox-collier-30mm-ext-high.html'],
            ["url" => 'https://bgmwinfield.fr/swampfox/3336-swampfox-independence-mount-msr-30mm.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/733-rehausse-bt-qds-a-leviers.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/1167-colliers-tsr-w-profil-medium-diam-34mm-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/868-tps-collier-tsr-w-profil-haut-diam-30mm-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/858-tps-collier-tsr-w-bas-profil-diametre-34mm-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/860-tps-collier-tsr-w-bas-profil-diametre-40mm-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/1170-colliers-tsr-w-profil-medium-diam-34mm-aluminium-anodise-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/1169-colliers-tsr-w-bas-profil-diam-34mm-aluminium-anodise-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/885-tps-collier-tsr-w-profil-haut-diametre-1-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/690-tps-collier-tsr-w-profil-medium-diametre-1-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/683-colliers-tsr-w-bas-profil-diam-1-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/863-tps-collier-tsr-w-profil-medium-diametre-30mm-aluminium-anodise-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/861-tps-collier-tsr-w-profil-medium-diametre-1-alu-anodise-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/856-tps-collier-tsr-w-aluminium-profil-bas-diametre-30mm.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/859-tps-collier-tsr-w-bas-profil-diametre-35mm-acier-phosphate-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/465-tps-collier-trac-en-diametre-30mm.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/472-tps-collier-cora-ii-en-diametre-30mm.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/469-tps-collier-cora-i-en-diametre-25-4mm.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/706-b-t-interface-picatinny-montage-basculant-pour-booster-x3-aimpoint.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1817-montage-alg-6-second-mount-t1-gris.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1817-montage-alg-6-second-mount-t1-gris.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1816-montage-alg-6-second-mount-t1-sable.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1815-montage-alg-6-second-mount-t1-noir.html'],
            ["url" => 'https://bgmwinfield.fr/colliers-et-embases-/733-rehausse-bt-qds-a-leviers.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1758-20-moa-dmr-scope-mount-2-cantilever-30-mm-samson-1757.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1757-20-moa-dmr-scope-mount-2-cantilever-34-mm-samson.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1613-dmr-scope-mount-3-cantilever-30-mm-samson.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/1614-dmr-scope-mount-2-cantilever-30-mm-samson-1613.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/565-aimpoint-montage-levier-m4s-ref-12198.html'],
            ["url" => 'https://bgmwinfield.fr/Montages/738-aimpoint-entretoise-39mm-pour-microt1-ref-12358.html'],
            ["url" => 'https://bgmwinfield.fr/Aimpoint/566-aimpoint-entretoise-30mm-pour-microt1-ref-12357.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2927-otis-ripcord-338-46-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2929-otis-ripcord-40-10mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2931-otis-ripcord-45-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2930-otis-ripcord-7-62mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2926-otis-ripcord-264-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2925-otis-ripcord-243-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2924-otis-ripcord-9mm-36-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2879-otis-ripcord-9mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2878-otis-ripcord-223-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2827-100-swabs-gun-cleaning-otis.html'],
            ["url" => 'https://bgmwinfield.fr/produits/1464-degraissant-500-ml.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2825-100-patches-coton-2.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2826-100-patches-coton-3-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2928-otis-ripcord-12ga-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2865-kit-de-nettoyage-patriot-12ga-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2863-kit-de-nettoyage-patriot-243-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2865-kit-de-nettoyage-patriot-12ga-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2866-kit-de-nettoyage-patriot-40mm-10mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2868-kit-de-nettoyage-patriot-9mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2867-kit-de-nettoyage-patriot-6-5mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2869-kit-de-nettoyage-patriot-cal-45-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2870-kit-de-nettoyage-rapide-12ga-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2872-kit-de-nettoyage-rapide-9mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2871-kit-de-nettoyage-rapide-7-62-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2873-kit-de-nettoyage-rapide-cal-40-10mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2874-kit-de-nettoyage-rapide-cal-45-otis.html'],
            ["url" => 'https://bgmwinfield.fr/autres-outils-/1061-gtul-pour-nettoyage-chargeur-glock-10mm-45acp.html'],
            ["url" => 'https://bgmwinfield.fr/autres-outils-/1198-gtul-pour-nettoyage-chargeur-glock-9mm-40s-w-357sig-45gap-1061.html'],
            ["url" => 'https://bgmwinfield.fr/autres-outils-/1421-baguette-de-nettoyage-poudre-noire-48-filetage-10-32-1420.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2862-kit-de-nettoyage-patriot-223-otis.html'],
            ["url" => 'https://bgmwinfield.fr/chiffonnettes/30-pro-shot-500-chiffonnettes-pour-calibre-12-16.html'],
            ["url" => 'https://bgmwinfield.fr/chiffonnettes/1547-pro-shot-1000-chiffonnettes-calibrees-pour-calibre-7mm-a-38-8mm.html'],
            ["url" => 'https://bgmwinfield.fr/ecouvillons-en-bronze-/768-pro-shot-ecouvillons-en-bronze-pour-calibre-22.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2933-kit-de-nettoyage-deluxe-cal-7-62-5-56-9mm-45-12ga-otis.html'],
            ["url" => 'https://bgmwinfield.fr/kits-de-nettoyage-/526-pro-shot-kit-de-nettoyage-universel-armes-de-poing.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2858-kit-de-nettoyage-complet-pistol-9mm-otis-2857.html'],
            ["url" => 'https://bgmwinfield.fr/kits-de-nettoyage-/525-pro-shot-kit-de-nettoyage-universel-armes-longues.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2851-7-62-star-chamber-tool-otis.html'],
            ["url" => 'https://bgmwinfield.fr/OTIS/2857-kit-de-nettoyage-complet-pistol-9mm-otis.html'],
            ["url" => 'https://bgmwinfield.fr/produits/41-militec-huile-synthetique-flacon-economique-de-473ml.html'],
            ["url" => 'https://bgmwinfield.fr/produits/189-militec-huile-synthetique-flacon-classique-de-236ml.html'],
            ["url" => 'https://bgmwinfield.fr/produits/3166-nettoyage-pour-silencieux-500ml-schletek.html'],
            ["url" => 'https://bgmwinfield.fr/produits/42-militec-huile-synthetique-flacon-de-118ml.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-de-culasse/2621-l2d-culasse-tyton-pour-glock-19-gen3-dlc-gris-metal.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-de-culasse/2622-l2d-culasse-tyton-pour-glock-19-gen3-alpine-multicam.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-de-culasse/2620-l2d-culasse-catalyst-pour-glock-17-gen3-dlc-gris-metal.html'],
            ["url" => 'https://bgmwinfield.fr/detentes-pour-armes-d-epaule/3159-detente-geissele-hk-mr-762.html'],
            ["url" => 'https://bgmwinfield.fr/crosses-pour-ar-15-et-ar-10/2061-mvb-arc-magpul.html'],
            ["url" => 'https://bgmwinfield.fr/montages-pour-visees-optiques/2561-geissele-super-precision-mount-ext-30mm-0-ddc.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2281-culasse-pour-glock-34-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2280-culasse-pour-glock-35-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee-pour-armes-d-epaule/2483-geissele-super-precision-mount-ext-30mm-0-noir-1.html'],
            ["url" => 'https://bgmwinfield.fr/montages-pour-visees-optiques/1886-geissele-super-precision-mount-ext-30mm-0-noir.html'],
            ["url" => 'https://bgmwinfield.fr/montages-pour-visees-optiques/1885-geissele-super-precision-mount-std-30mm-0-noir.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/2917-garde-main-urx-31-1075-knights-armament.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/2915-garde-main-urx-31-15-knights-armament.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/903-culasse-pour-glock-17l-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/902-culasse-pour-glock-35.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/901-culasse-pour-glock-34-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-de-culasses/3131-geissele-rebcg-culasse-transporteur.html'],
            ["url" => 'https://bgmwinfield.fr/rainier-arms/3897-rainier-arms-canon-mountain-series-cold-hammer-forged-556-16-mid-weight.html'],
            ["url" => 'https://bgmwinfield.fr/detentes-detentes-match/2824-detente-match-geissele-super-apc.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/1716-garde-main-rhino-arms-ap-custom-genii-126-rifle.html'],
            ["url" => 'https://bgmwinfield.fr/culasses-et-pieces-associees-pour-ar-15-et-ar-10/3572-faxon-firearms-transporteur-allege-tete-de-culasse-nitride-cameleon.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/1715-garde-main-rhino-arms-ap-custom-genii-71-4-carbine.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/3158-garde-main-geissele-mk16-93-noir.html'],
            ["url" => 'https://bgmwinfield.fr/gardes-mains/3016-garde-main-geissele-mk16-135-usasoc-sopmod-noir.html'],
            ["url" => 'https://bgmwinfield.fr/crosses-pour-ar-15-et-ar-10/3049-cmmg-ar15-receiver-extension-and-stock-kit-ripstock-standard.html'],
            ["url" => 'https://bgmwinfield.fr/garde-main-pour-ar-15-et-ar-10/3157-garde-main-geissele-super-modular-rail-mk8-95-noir.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/905-culasse-pour-glock-21-sf-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2292-culasse-pour-glock-27-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2291-culasse-pour-glock-17-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2289-culasse-pour-glock-19-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2287-culasse-pour-glock-22-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2286-culasse-pour-glock-23-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2285-culasse-pour-glock-26-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2284-culasse-pour-glock-31-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2283-culasse-pour-glock-32-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/2282-culasse-pour-glock-33-gen3-complete.html'],
            ["url" => 'https://bgmwinfield.fr/crosses-pour-ar-15-et-ar-10/1554-crosse-ubr-noire-magpul.html'],
            ["url" => 'https://bgmwinfield.fr/Crosses/2026-crosse-magpul-prs-gen3-noire.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/896-culasse-pour-glock-33-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/895-culasse-pour-glock-32-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/894-culasse-pour-glock-31-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/893-culasse-pour-glock-28-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/892-culasse-pour-glock-26-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/891-culasse-pour-glock-23-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/890-culasse-pour-glock-22-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/889-culasse-pour-glock-27-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/888-culasse-pour-glock-19-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/887-culasse-pour-glock-17-gen3.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1688-lantac-dragon-dgn762b.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1687-lantac-dragon-dgn556b.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/918-canon-glock-19c.html'],
            ["url" => 'https://bgmwinfield.fr/pieces-d-origine-glock/917-canon-glock-17c.html'],
            ["url" => 'https://bgmwinfield.fr/leviers-d-armement-pour-ar-15-et-ar-10/3018-geissele-super-charging-handle-levier-darmement-762-noir.html'],
            ["url" => 'https://bgmwinfield.fr/crosses-pour-ar-15-et-ar-10/3644-bcm-stock-kit-mod-1-sopmod-compartment-black.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee-pour-armes-d-epaule/3161-geissele-backup-iron-rear-sight.html'],
            ["url" => 'https://bgmwinfield.fr/montages-pour-visees-optiques/3140-montage-geissele-super-precision-mro-lower-1-3-co-witness.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee-pour-armes-d-epaule/2116-magpul-mbus-pro-offset-oeilleton-deporte.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee-pour-armes-d-epaule/3160-guidon-geissele-repliable-buis.html'],
            ["url" => 'https://bgmwinfield.fr/buffers-pour-ar-15-et-ar-10/3017-geissele-super-42-buffer-spring-h3.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee/680-oeilleton-samson-repliable.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee/679-guidon-samson-repliable-modele-2.html'],
            ["url" => 'https://bgmwinfield.fr/montages-pour-visees-optiques/2054-montage-geissele-t-1-t-2-absolute-co-witness.html'],
            ["url" => 'https://bgmwinfield.fr/montages-pour-visees-optiques/2053-montage-geissele-t-1-t-2-lower-1-3-co-witness.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes/1683-bravo-company-mfg-mod-0-5-56.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/3027-griffin-armament-qd-m4sd-frein-de-bouche.html'],
            ["url" => 'https://bgmwinfield.fr/compensateurs-et-cache-flammes-pour-ar-15-et-ar-10/1887-precision-armament-m4-72-severe-duty-cal-223.html'],
            ["url" => 'https://bgmwinfield.fr/organes-de-visee/1508-magpul-mbus-pro-guidon.html'],
            ["url" => 'https://bgmwinfield.fr/elements-d-armes-de-poing-reglementes/1080-keltec-canon-filete-avec-cache-flamme-pour-pmr-30.html'],
            ["url" => 'https://bgmwinfield.fr/Inforce/364-inforce-lampe-tactique-modele-9v-couleur-sable.html'],
            ["url" => 'https://bgmwinfield.fr/Inforce/352-inforce-lampe-tactique-modele-9v-couleur-noire.html'],

        ];

        $dima = [
            ["url" => 'https://www.dimatex.fr/fr/sacs/636-braco-coyote-3701370612745.html'],
            ["url" => 'https://www.dimatex.fr/fr/black-line/102-matt-black-line.html'],
            ["url" => 'https://www.dimatex.fr/fr/polygone/3096-malette-polygone-3701370616934.html'],
            ["url" => 'https://www.dimatex.fr/fr/sacs/3486-sac-a-dos-matt-black-series.html'],
            ["url" => 'https://www.dimatex.fr/fr/black-series/3200-malette-polygone-3701370617016.html'],
            ["url" => 'https://www.dimatex.fr/fr/black-series/3464-mallette-control-17-black-series-3701370617825.html'],
            ["url" => 'https://www.dimatex.fr/fr/black-series/3487-porte-documents-sentinel-black-series.html'],
            ["url" => 'https://www.dimatex.fr/fr/la-boutique/3901-sac-de-paquetage-sabrex-3701370617894.html'],
            ["url" => 'https://www.dimatex.fr/fr/la-boutique/3872-valise-bluedog-full-black-3701370618129.html'],
            ["url" => 'https://www.dimatex.fr/fr/black-line/1653-ventura-dimatex-3701370607734.html'],
            ["url" => 'https://www.dimatex.fr/fr/paquetage/132-barack-noir-3701370608939.html'],
            ["url" => 'https://www.dimatex.fr/fr/paquetage/131-barack-bleu-nuit-3701370608946.html'],
            ["url" => 'https://www.dimatex.fr/fr/paquetage/1287-patton-full-black-3701370608137.html'],
            ["url" => 'https://www.dimatex.fr/fr/paquetage/1286-patton-black-line-3701370608151.html'],
            ["url" => 'https://www.dimatex.fr/fr/paquetage/135-jfk-noir.html'],
            ["url" => 'https://www.dimatex.fr/fr/paquetage/1473-jfk-bleu-marine.html'],
        ];
        $humbert = [
            "9b_Tikka_accessoires23origin.xlsx",
            "13a-AIMPOINT_Optiques23.xlsx",
            "10b_RUGER_revolver_pistolet23.xlsx",
            "9c_Tikka_moderateur23.xlsx",
            "8b-Sako_accessoires23.xlsx",
            "13b_AIMPOINT-Pieces23.xlsx",
            "3b_BERETTA_TIR_DEFENSE_ACCESSOIRE23.xlsx",
            "2b_BERETTA_Accessoires23.xlsx",
            "1b_BERETTA_Juxtapose23.xlsx",
            "11c-Uberti-piece23.xlsx",
            "11a-Uberti_carabine23.xlsx",
            "5b_BENELLLI_accessoires23.xlsx",
            // "20_FOB23.xlsx",
            "18_WEAVER23.xlsx",
            "16b_TRIJICON_Pieces23.xlsx",
            "16a_TRIJICON_Optiques23.xlsx",
            "15b_BURRIS_Pieces23.xlsx",
            "8c-Sako_munitions22 - double page23.xlsx",
            "14b_STEINER_Pieces23.xlsx",
            "15a_BURRIS_Optiques23.xlsx",
            "15b_BURRIS_Pieces23.xlsx",
        ];
        $riv = [
            ['url' => "https://www.arsenal-pro.fr/compte"],
            ["url" => "https://www.rivolier.com/carabine-hatsan-c-22lr-bois.html"],
        ];

        // $this->supplier->subCategoryEuropArms();
        //EXEMPLE SCRAPPING BGM WINFIELD TEST
        $this->supplier->insertBgmWinfield($bgm1);
        //INSERT PRODUIT A10 TEST
        // $this->supplier->insertA10();
        //SCRAPPING DIMATEX TEST
        //$this->supplier->insertProduitDimatex($dima);
        //TEST INSERT DCA
        //$this->supplier->insertDCAFrance();
        // foreach($humbert as $hum){ //insertion humbert
        //     $this->supplier->insertHumbert("./suppliers/humbert/" . $hum,"Humbert"); 
        // }
        $this->supplier->produitAssociationSetter();
        return Command::SUCCESS;
    }
}
